Cargo.toml
src/examples/example_compose_extrinsic_offline.rs
src/extrinsic/mod.rs

closes #18 
- added compose_extrinsic_offline macro
- added an example accordingly

Cl compose extrinsic offline

---

src/extrinsic/mod.rs

hopefully fixed macro deps for external usage

---

Cargo.toml
primitives/Cargo.toml
primitives/src/child_storage_key.rs
primitives/src/crypto.rs
primitives/src/hexdisplay.rs
primitives/src/lib.rs
primitives/src/offchain.rs
primitives/src/storage.rs
primitives/src/testing.rs
primitives/src/traits.rs
test_no_std/Cargo.toml

- Working Example gainst a the substrate-test-node on some revision
- TODO: Adjust test_no_std dependencies after worker update

updated to f17d023bbe179f15678ac9989f471c9b18917e17

---

src/utils.rs

adds double_map storage support

resolving #34

---

Cargo.toml
src/examples/example_sudo.rs
src/extrinsic/mod.rs
src/extrinsic/xt_primitives.rs
src/lib.rs

closes #38 
new sudo extrinsic example
added low-level getters as well

add sudo example

---

Cargo.toml
src/examples/example_benchmark_bulk_xt.rs
src/examples/example_compose_extrinsic_offline.rs
src/examples/example_contract.rs
src/examples/example_custom_storage_struct.rs
src/examples/example_generic_extrinsic.rs
src/examples/example_sudo.rs
src/examples/example_transfer.rs
src/lib.rs
src/rpc/client.rs
src/rpc/mod.rs

fixes #53 
no_std not building yet

send multiple extrinsics without waiting for finalization

---

src/rpc/client.rs

As I [stated](https://github.com/scs/substrate-api-client/issues/68#issuecomment-622381438) in #68 earlier, treating all rpc errors like `None` and substituting it with "nix" is very mutch error-prone. 
Passing the error on the other hand behaves similarly but makes debug easier.
So in case of error, [this log](https://github.com/scs/substrate-api-client/blob/23b6255502141559fef42fafd7032704c5dd1f46/src/lib.rs#L338) will give you exact error from node.
ps. the error in test is real btw

change the way to parse errors

---

src/examples/example_get_blocks.rs
src/lib.rs

* added `get_signed_block` api call
* added `api.get_opaque_storage_by_key_hash`

add api.get_signed_block + api.get_opaque_storage_by_key_hash

---

.githooks/README.md
Cargo.toml
Jenkinsfile
src/examples/example_benchmark_bulk_xt.rs
src/examples/example_compose_extrinsic_offline.rs
src/examples/example_event_callback.rs
src/examples/example_generic_event_callback.rs
src/examples/example_generic_extrinsic.rs
src/examples/example_get_blocks.rs
src/examples/example_get_storage.rs
src/examples/example_print_metadata.rs
src/examples/example_sudo.rs
src/examples/example_transfer.rs
src/lib.rs
src/rpc/client.rs
src/rpc/mod.rs

- Use the new test-node
- Update of Jenkinsfile
- Copy first because of file permissions
- Comment sudo example as it generates an error
This fixes #71

use substrate-api-client-test-node

---

src/examples/example_get_blocks.rs
src/lib.rs
src/rpc/client.rs
src/rpc/json_req.rs
src/rpc/mod.rs

added rpc call: `chain_subscribeFinalizedHeads`

subscribe finalized heads

---

Cargo.lock
Cargo.toml
README.md
src/examples/example_benchmark_bulk_xt.rs
src/examples/example_compose_extrinsic_offline.rs
src/extrinsic/mod.rs
src/extrinsic/xt_primitives.rs
src/rpc/client.rs
test_no_std/Cargo.lock
test_no_std/Cargo.toml
test_no_std/src/main.rs
tutorials/api-client-tutorial/Cargo.toml

Upgrade upstream v2.0.0 rc5

---

Cargo.lock
Cargo.toml
client-keystore/Cargo.toml
client-keystore/src/lib.rs

Seems to be a dependency issue.. not a keystore issue itself.

Keystore bug fix

---

Cargo.lock
Cargo.toml
client-keystore/Cargo.lock
client-keystore/Cargo.toml
src/examples/example_event_callback.rs
test_no_std/Cargo.lock
tutorials/api-client-tutorial/Cargo.lock

Update to substrate v4.0.0 dev

---

.github/workflows/build-test-clippy.yml
Cargo.lock
Cargo.toml
client-keystore/Cargo.toml
test_no_std/Cargo.lock
test_no_std/Cargo.toml
tutorials/api-client-tutorial/Cargo.lock
tutorials/api-client-tutorial/Cargo.toml

change to polkadot-v0.9.2

---

src/std/rpc/ws_client/mod.rs

Fixes #135 
Maybe there's a more elegant solution, but it does fix the issue.

add end_process to error response

---

Cargo.toml
Jenkinsfile
src/examples/example_event_error_details.rs
src/examples/example_print_metadata.rs
src/std/node_metadata.rs
src/std/rpc/ws_client/events.rs
src/std/rpc/ws_client/mod.rs

and add example_event_error_details to test/show how to use the wait_for_event

Fix issue #138 

---

src/std/mod.rs

Fixing `InclusionFee<>` conversion

Fix calculating InclusionFee

---

Cargo.toml
node-api/src/metadata.rs
src/examples/example_print_metadata.rs

example-print-metadata is running as previously
* Closes #179

Metadata v14 pretty prints 

---

Cargo.lock
src/examples/example_benchmark_bulk_xt.rs
src/examples/example_compose_extrinsic_offline.rs
src/examples/example_event_callback.rs

* https://github.com/paritytech/substrate/commit/1d8f7bf6de1f447b706a121c83e759da807d3a01

bump substrate@1d8f7b

---

src/examples/example_get_blocks.rs
src/std/mod.rs

add : `get_block_hash`, `get_block_by_num`, `get_signed_block_by_num`, `ApiClientError::Custom(dyn Box<std::Error>`

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
client-keystore/Cargo.toml
node-api/Cargo.toml
node-api/src/error.rs
node-api/src/storage.rs
primitives/Cargo.toml
rust-toolchain.toml
src/std/mod.rs
tutorials/api-client-tutorial/Cargo.toml

Last commit before a breaking change where AccountId does no longer derive default.

bump substrate@b9cafb

---

Cargo.lock
test-no-std/src/main.rs

update substrate dep to 9a6d706d8db00abb6ba183839ec98ecd9924b1f8

---

src/std/rpc/ws_client/client.rs

This is a proposal to reduce the number of threads that we spawn. As far as I can see this is a backward compatible change as it does not affect the public API or the externally visible blocking behavior. Please check my reasoning carefully.
In many cases we spawn the thread in `start_rpc_client_thread(..)` and then immediately call the blocking `recv()` function. Then we have two threads that are waiting in a blocking manner. 
Instead we can make the `connect()` in a blocking manner directly and wait there. The `recv()` afterwards will then not be blocking anymore (as there is already data in the channel). This saves spawning a thread and additional scheduling overhead. 
See attached system call numbers to see the improvements when running our benchmark for 3 minutes. 
- Overhead due to …

Provide a connect method that does not spawn a thread

---

.github/workflows/ci.yml
.taplo.toml
Cargo.toml
client-keystore/Cargo.toml
node-api/Cargo.toml

- best config to match coding guidelines
- according to https://github.com/integritee-network/worker/issues/957
- enforces formatting of Cargo.toml in the CI

Add cargo.toml formatting with taplo

---

src/std/mod.rs

Remove unnecessary clone restrictions

---

Cargo.toml
compose-macros/Cargo.toml
examples/example_event_callback.rs
examples/example_get_account_identity.rs
node-api/Cargo.toml
primitives/Cargo.toml
primitives/src/extrinsics.rs
src/std/mod.rs

Harmonize .tomls and the substrate import names. No logical changes at all.

Clean up and harominze toml files

---

README.md

add encointer to used projects

Add encointer to used projects in README

---

.github/workflows/ci.yml
Cargo.lock
about.hbs
about.toml

Add license check to CI

---

client-keystore/src/lib.rs
node-api/src/print_metadata.rs
rust-toolchain.toml
src/api/rpc_api/author.rs
src/rpc/error.rs

Update toolchain to 2023-01-05

---

Cargo.lock

Update to newest substrate commit + cargo update

---

primitives/src/extrinsics/signer.rs

Fix Signer encoding

---

docs/README.md

Add semantic versioning explanation to developer doc

---

Cargo.toml
README.md
compose-macros/src/rpc.rs

See my comment in the issue: https://github.com/scs/substrate-api-client/issues/546#issuecomment-1521455679
Closes #546

Add documentation for the websocket features

---

Cargo.lock
node-api/Cargo.toml
node-api/src/scale_value/encode.rs

Update scale-bits and scale-encode

---

Cargo.lock
node-api/Cargo.toml

Update scale-enode and decode to crates.io

---

examples/examples/runtime_update_async.rs

I ran the test multiple times and it seems to pass more reliably now

Increase timeout value

---

Cargo.lock
examples/examples/get_account_identity.rs

`cargo update` and updated identity pallet which changed on parity side.
closes #659

Update all dependencies with `cargo update`

---

.github/workflows/ci.yml

Add `release-polkadot-vx.x.x` to automatic CI run trigger

---

node-api/Cargo.toml

Reasoning: Makes it easier for replace and search in case of polkadot-branch updates

Fix feature order in node-api toml

---

Cargo.lock
Cargo.toml
client-keystore/Cargo.toml
client-keystore/src/lib.rs

Update tungstenite and array-bytes

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
client-keystore/src/lib.rs
examples/async/Cargo.toml
examples/sync/Cargo.toml
node-api/Cargo.toml
node-api/src/storage.rs
primitives/Cargo.toml
primitives/src/extrinsics/extrinsic_params.rs
rust-toolchain.toml
src/lib.rs
src/rpc/error.rs
testing/async/Cargo.toml
testing/async/examples/author_tests.rs

Update rust-toolchain and dependencies

---

docs/README.md

Noticed that there was nothing concrete for these things, so I added it now. Hopefully this help a little.

Add TODO lists to developer docs

---

.github/workflows/ci.yml
examples/async/examples/unstable_rpc_api_calls.rs

Add unstable rpc api calls example

---

docs/README.md

Update release TODO list with crates.io

---

Cargo.lock
Cargo.toml
compose-macros/Cargo.toml
examples/async/Cargo.toml
examples/sync/Cargo.toml
examples/wasm/Cargo.toml
keystore/Cargo.toml
node-api/Cargo.toml
primitives/Cargo.toml
test-no-std/Cargo.toml
testing/async/Cargo.toml
testing/sync/Cargo.toml

Update crate version numbers

---

Cargo.lock
Cargo.toml
compose-macros/Cargo.toml
examples/async/Cargo.toml
examples/sync/Cargo.toml
examples/wasm/Cargo.toml
keystore/Cargo.toml
node-api/Cargo.toml
primitives/Cargo.toml
test-no-std/Cargo.toml
testing/async/Cargo.toml
testing/sync/Cargo.toml

Bump to new release version (closes #812 )

Bump to v1.17

---

Cargo.lock
api-client/Cargo.toml
compose-macros/Cargo.toml
docs/README.md
examples/async/Cargo.toml
examples/sync/Cargo.toml
examples/wasm/Cargo.toml
keystore/Cargo.toml
node-api/Cargo.toml
primitives/Cargo.toml
test-no-std/Cargo.toml
testing/async/Cargo.toml
testing/sync/Cargo.toml

Other than the adjustment of version numbers two additional small changes due to the re-structuring of the workspace:
- Adjust path to README.md
- Fix instructions for publishing

Update internal version numbers

---

api-client/src/api/api_client.rs
node-api/src/events/raw_event_details.rs

Refer to variables directly in formatting-string for log messages

Fix nightly build
