scs/substrate-api-client

- src/rpc/json_req.rs
allows lib user to specify id for each RPC subscription. necessary if there's more than one
> adding option to select json request id

- Jenkinsfile
- src/lib.rs
- src/utils.rs
this is tested against encointer-node.
There is a caveat:
the runtime module has to define the double_map with blake2_256 hasher, not twox128. We could add functions for both, but shawns tutorial silently assumes blake2
this works:
```
decl_storage! {
trait Store for Module<T: Trait> as EncointerCeremonies {
ParticipantRegistry get(participant_registry): double_map CeremonyIndexType, blake2_256(ParticipantIndexType) => T::AccountId;
}
}
```
> adding pub fn for double map storage

- Cargo.toml
- ci/install_rust.sh
- src/examples/example_compose_extrinsic_offline.rs
- src/examples/example_contract.rs
- src/examples/example_custom_storage_struct.rs
- src/examples/example_event_callback.rs
- src/examples/example_generic_extrinsic.rs
- src/examples/example_get_storage.rs
- src/examples/example_print_metadata.rs
- src/examples/example_sudo.rs
- src/examples/example_transfer.rs
- src/extrinsic/balances.rs
- src/extrinsic/contract.rs
- src/extrinsic/xt_primitives.rs
- src/lib.rs
- src/node_metadata.rs
- src/rpc/client.rs
- src/utils.rs
- test_no_std/Cargo.toml
- tutorials/api-client-tutorial/Cargo.toml
- tutorials/api-client-tutorial/src/main.rs
* upstream upgrade
** updated storage_key_hash computation
** replaced get_fee_balance with get_account_data
examples work except for compose_exctrinsic_offline and example_contract, which is the status_quo from before.
> Upstream upgrade 00a400f82539e2f78e8ddbcd98aea512c87c5f3c

- src/events.rs
- src/lib.rs
Add Moment type for those who used it. Got several failed api calls failed otherwise.
> events: register Moment type

- src/examples/example_get_blocks.rs
- src/lib.rs
* `get_header` and `get_block` now return generics with the `Header`, `Block` trait bound
* get_finalized_head now returns `Option<Hash>`
* Unecessary `Clone` trait bound is removed from `get_storage_value` and `get_storage_by_keyhash`
> Small api changes

- src/events.rs
- src/examples/example_generic_event_callback.rs
- src/lib.rs
api.wait_for_event now takes Option<EventsDecoder> as argument such that a user is able to extend the encoder with custom primitive types
* tested with substratee-client example
> user-extendable-eventdecoder

- src/lib.rs
- src/rpc/client.rs
- src/rpc/mod.rs
`send_extrinsic` can now take `XtStatus::InBlock` and `XtStatus::Broadcast` as statuses to exit on.
* Add `XtStatus::InBlock` and `XtStatus::Broadcast` cases to `send_extrinsic`
* Add `send_extrinsic_and_wait_until...` functions for `InBlock` and `Broadcast` to the rpc module
* Implement `on_extrinsic_msg_until...` functions in the rpc client
* Add tests against `parse_status` for `Inblock` and `Broadcast
Modified `example_generic_extrinsic` (ln 51) to:
```rust
let tx_hash = api
.send_extrinsic(xt.hex_encode(), XtStatus::InBlock)
.unwrap();
println!("[+] Transaction got in block. Hash: {:?}", tx_hash);
```
Console output using `RUST_LOG=debug cargo run --example example_generic_extrinsic`:
```
...
2020-05-01T08:11:06Z DEBUG substrate_api_client::rpc::client] got msg …
```
> Add ability to exit on InBlock and Broadcast status for send_extrinsic

- Jenkinsfile
- src/extrinsic/xt_primitives.rs
There was an unneccesarry decode trait bound on signed-payload.
This interfered with the `OpaqueCall` struct defined in the substratee-worker, that only implements encode and on purpose does not implement decode.
> remove unnecessary decode trait bound.

- src/examples/example_benchmark_bulk_xt.rs
- src/examples/example_compose_extrinsic_offline.rs
- src/extrinsic/mod.rs
- src/extrinsic/xt_primitives.rs
PR referencing Issue #88 
- mortal era for compose_extrinsic_offline macro
- example_benchmark_bulk_xt updated to use macro
- example_compose_extrinsic_offline updated to use macro
> Allow for immortal transactions in compose_extrinsic_offline macro

- src/examples/example_get_storage.rs
- src/lib.rs
- src/node_metadata.rs
- src/rpc/json_req.rs
This may be useful for getting keys with key prefix in storage maps
- use `state_getKeys` in json_req
- add `get_storage_map_key_prefix` method for api client
> get map key prefix

- Cargo.lock
- Cargo.toml
- src/extrinsic/mod.rs
- src/lib.rs
- test_no_std/Cargo.lock
re-export sp_runtime such that third parties importing the api-client do not need to depend on it if the use the compose macros.
Closes #97
> Re export sp_runtime

- Cargo.toml
- client-keystore/Cargo.toml
Necessary from v 0.4.3 on - otherwise decode will not work in no-std environment anymore
> add alloc feature to no-std hex

- test_no_std/Cargo.lock
- test_no_std/Cargo.toml
Currently, this changes nothing, but this is an improvement of the cargo dependency resolution that might prevent `std` leakage into `no_std` builds for dev-dependencies of procedural macros. See: https://github.com/paritytech/substrate/issues/8891
> [test_no_std] add `resolver = 2` in toml

- Cargo.lock
- Cargo.toml
- src/extrinsic/balances.rs
- src/extrinsic/contract.rs
- src/extrinsic/mod.rs
- src/extrinsic/staking.rs
- src/std/mod.rs
- src/std/rpc/json_req.rs
- src/std/rpc/mod.rs
- src/std/rpc/ws_client/mod.rs
- test_no_std/Cargo.lock
- tutorials/api-client-tutorial/Cargo.lock
Overview:
- Added the most common (in my opinion) staking extrinsics
- Added api call for getting fee details (payment_queryFeeDetails)
~~The custom `FeeDetails` and `InclusionFee` are added because we would need both `pallet-transaction-payment` and `sp-rpc` (for `NumberOrHex`), which is quite a lot of extra stuff.~~
~~It also may not be necessary to add the entire `pallet-staking` crate, if we are ok with adding a copy of `RewardDestination`. I'm not sure if this pallet will be useful for anything else in the future. Please let me know and I will remove the import.~~
> Add staking extrinsics

- Cargo.lock
- Cargo.toml
- test_no_std/Cargo.lock
- test_no_std/Cargo.toml
This removes the need to depend on `sp-application-crypto` in the depending crate  when the api-client is used in a no_std environment.
> fix + remove full-crypto feature flag and make it implicit.

- src/std/mod.rs
Changed return type of get_fee_details() from FeeDetails<NumberOrHex> to
FeeDetails<Balance> to make it more usable.
> Change return type of Api::get_fee_details()

- Cargo.lock
- src/examples/example_get_storage.rs
* upgrade to paritytech/substrate@558a68f
* dropped StorageDoubleMap in template and get_storage example. too painful to maintain
> upgrade substrate to 558a68f and drop StorageDoubleMap example

- src/examples/example_transfer.rs
- src/lib.rs
- src/std/rpc/mod.rs
- src/std/rpc/ws_client/client.rs
- src/std/rpc/ws_client/mod.rs
I was having the impression that we get a certain lag when the enclave tries to submit extrinsics in the ocall.
So I tried to add `send_extrinsic` variant that is even faster than waiting for  `XtStatus::Ready`. I was having trouble finding out, what the exact checks are when you wait until ready. So, I just implemented it and wanted to test it.
Subjectively, I am not confident that it makes a difference. @brenzi, @haerdib  do you know if this is even worth implementing?
> Add `XtStatus::SubmitOnly`

- Cargo.lock
- Cargo.toml
- src/examples/example_get_blocks.rs
Closes #165.
This was such a low-hanging fruit that I just needed to tackle it.
@haerdib can you update jenkins to use the node-template from substrate instead?
> remove scs node-template dependency

- src/std/mod.rs
- src/std/rpc/json_req.rs
Extending API with `get_payment_info`. Thanks to that it is possible to know the `unadjusted_fee` for transaction, i.e. a raw fee before applying configurable multipliers. Useful for testing fee adaptation in e2e tests.
> Add querying for payment info

- src/std/error.rs
- src/std/mod.rs
Without Send + Sync it's not possible to use the ApiError within threads
(turned out to be a problem here : https://github.com/integritee-network/worker/blob/feature/fm-sidechain-peer-fetch-client/core/rpc-server/src/lib.rs#L68)
> Move ApiError to separate file and add Send + Sync

- src/examples/example_contract_instantiate_with_code.rs
- src/extrinsic/contract.rs
I added support for `instantiate_with_code` contracts API call + example usage.
> Add instantiate_with_code

- Cargo.lock
- Cargo.toml
- client-keystore/Cargo.toml
- node-api/src/error.rs
- src/examples/example_benchmark_bulk_xt.rs
- src/examples/example_compose_extrinsic_offline.rs
- src/examples/example_contract.rs.DEPRECATED
- src/examples/example_contract_instantiate_with_code.rs
- src/examples/example_custom_storage_struct.rs.DEPRECATED
- src/examples/example_event_error_details.rs
- src/examples/example_generic_extrinsic.rs
- src/examples/example_get_storage.rs
- src/examples/example_sudo.rs
- src/examples/example_transfer.rs
- tutorials/api-client-tutorial/Cargo.toml
Once again, a necessary version bump, due to sp-keyring update to v5.0.0...
https://github.com/paritytech/substrate/commit/59649dd117969467d8046df86afe56810f596545
> bump substrate version to 59649dd

- node-api/src/metadata.rs
- node-api/src/storage.rs
- src/std/mod.rs
Removes unused default value from the StorageMaps. It was not used and blocked OptionQueries by throwing `MapValueTypeError`s when querying an Option Value.
Tested with recent node and worker (https://github.com/integritee-network/worker/pull/645)
> Remove unused default value in StorageMaps to allow OptionQuery

- .github/workflows/ci.yml
- compose-macros/src/lib.rs
- examples/example_benchmark_bulk_xt.rs
- examples/example_compose_extrinsic_offline.rs
- examples/example_contract_instantiate_with_code.rs
- examples/example_event_callback.rs
- examples/example_event_error_details.rs
- examples/example_generic_event_callback.rs
- examples/example_generic_extrinsic.rs
- examples/example_get_blocks.rs
- examples/example_get_existential_deposit.rs
- examples/example_get_storage.rs
- examples/example_print_metadata.rs
- examples/example_sudo.rs
- examples/example_transfer.rs
- primitives/src/extrinsic_params.rs
- primitives/src/extrinsics.rs
- primitives/src/lib.rs
- src/extrinsic/balances.rs
- src/extrinsic/contract.rs
- src/lib.rs
- src/std/mod.rs
- src/std/rpc/ws_client/mod.rs
- tutorials/api-client-tutorial/src/main.rs
- According to subxt, add ExtrinsicParams and BaseExtrinsicParamsBuilder to configure the signed extra. The tip type can be defined for the API.
- If no extra params are defined, the default one will be used. Default values are defined as in subxt
- Let the GenericExtras as it was.
- Some examples don't run locally: get_blocks, benchmark and compose xt offline. These don't run in master too
> Support Asset payment

- examples/example_benchmark_bulk_xt.rs
- examples/example_compose_extrinsic_offline.rs
- examples/example_generic_extrinsic.rs
- examples/example_sudo.rs
- primitives/src/extrinsic_params.rs
- primitives/src/extrinsics.rs
- src/extrinsic/balances.rs
- src/extrinsic/contract.rs
This is to make the extrinsics truly generic over the signed extra, which can now be completely configured outside this crate if needed
> [exrinsics] make generic over signed extra

- compose-macros/src/lib.rs
- examples/example_benchmark_bulk_xt.rs
- examples/example_compose_extrinsic_offline.rs
- examples/example_generic_extrinsic.rs
- examples/example_sudo.rs
- primitives/src/extrinsic_params.rs
- primitives/src/extrinsics.rs
- src/extrinsic/balances.rs
- src/extrinsic/contract.rs
- src/std/mod.rs
- tutorials/api-client-tutorial/src/main.rs
Fix issue #233
- add generic type in ExtrinsicParams for the Signed Extra and the AdditionalSigned
- SignedPayload is generic over SignedExtra and AdditionalSigned
- UncheckedExtrinsicV4  is generic over SignedExtra
- Define default SignedExtra and AdditionalSigned (previously GenericExtra and AdditionalSigned)
- Add function to api client to get the ExtrinsicParams to make the macro compose_extrinsic_offline generic
- compose_extrinsic_offline generic interface change !!! The Signed Extra and the AdditionalSigned are build before
> Become generic over SignedExtra and AdditionalSigned

- src/utils.rs
The function showed up on some of my benchmarks therefore it is at least somewhat relevant to performance.
We could also change the API to use &str but that would be a breaking API change
> Remove unnecessary calls to to_string() to improve performance.

- .github/workflows/ci.yml
- src/std/error.rs
The value NodeApi used in the impl block has already the very same feature flag.
> Add ws-client feature flag for impl block

- Cargo.lock
- Cargo.toml
- node-api/Cargo.toml
- test-no-std/Cargo.toml
- test-no-std/src/main.rs
This gives more flexibility by letting the user decide whether the static assertions shall be enabled or not.
> Expose `disable_target_static_assertions` feature flag 

- Cargo.lock
- Cargo.toml
- node-api/Cargo.toml
- node-api/src/events.rs
- node-api/src/lib.rs
- node-api/src/metadata.rs
- node-api/src/storage.rs
- src/lib.rs
- src/std/error.rs
- src/std/mod.rs
- src/utils.rs
- required for  https://github.com/integritee-network/worker/issues/113
- metadata can be coded and decoded. Use of integritee frame-metadata fork  : https://github.com/integritee-network/frame-metadata
> Metadata sgx compatible

- Cargo.lock
- Cargo.toml
- examples/example_benchmark_bulk_xt.rs
- examples/example_compose_extrinsic_offline.rs
- examples/example_event_callback.rs
Changes:
* bump substrate to https://github.com/paritytech/substrate/commit/427fd09bcb193c1e79dec85b1e207c718b686c35
* patch ed25519-zebra to fix no_std build Closes #271. Will track the possibility of unpatching in #286.
> bump substrate and patch ed25519-zebra

- .github/workflows/ci.yml
>Starting today runner version 2.298.2 will begin to warn you if you use the save-state or set-output commands via stdout. We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.
---
See https://github.com/Swatinem/rust-cache/issues/80 and https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> GHA: update `rust-cache` to v2, as v1 contains deprecated commands (`save-state` and `set-output`)

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- examples/example_benchmark_bulk_xt.rs
- examples/example_compose_extrinsic_offline.rs
- examples/example_event_callback.rs
- examples/example_event_error_details.rs
- examples/example_generic_event_callback.rs
- examples/example_generic_extrinsic.rs
- examples/example_get_blocks.rs
- examples/example_get_existential_deposit.rs
- examples/example_get_storage.rs
- examples/example_print_metadata.rs
- examples/example_sudo.rs
- examples/example_transfer.rs
- primitives/src/extrinsics.rs
Use `parity/substrate:latest` to run a node for the examples. Removes the need to build our own node template.
- The substrate docker image does not use the node-template runtime but the [`kitchensink-runtime`](https://github.com/paritytech/substrate/blob/c11b2621e6e0e20263a230b783d68820370f9ee1/bin/node/runtime/src/lib.rs). 
Good thing: it now includes more pallets, leaving more options to test examples in CI.
- update to substrate commit `c24431eb6a95197550b30715a4c124be1aea79de` to include a substrate fix for the uniques  pallet: https://github.com/paritytech/substrate/pull/12297
Closes #204
Replaces PR #249
> Use substrate kitchensink-runtime docker image in CI

- Cargo.lock
- Cargo.toml
- client-keystore/src/lib.rs
- node-api/Cargo.toml
- rust-toolchain.toml
- src/std/rpc/ws_client/client.rs
- src/std/rpc/ws_client/mod.rs
- src/utils.rs
- update polkadot version to master of v0.9.30
- update rust toolchain to 2022-11-05
- fix clippy lints
closes #300 
Follow up issue due to the clippy warnings: https://github.com/scs/substrate-api-client/issues/303 or https://github.com/scs/substrate-api-client/issues/267.
Didn't want to introduce any breaking interface changes in this PR.
> update to polkadot version v0.9.30

- Cargo.lock
update to substrate commit [696bdc67af5fd83aca318263dbd405593b043ba3](https://github.com/paritytech/substrate/commit/696bdc67af5fd83aca318263dbd405593b043ba3), which matches the polkadot-v0.9.31 branch
closes #301
> update to polkadot-v0.9.31

- .github/workflows/ci.yml
- examples/example_custom_nonce.rs
- examples/example_event_callback.rs
- examples/example_get_blocks.rs
- src/std/error.rs
- src/std/mod.rs
- src/std/rpc/mod.rs
- src/std/rpc/ws_client/client.rs
- src/std/rpc/ws_client/mod.rs
- Adds a custom nonce example which additionally checks the future return error
- The `ThreadOut Message` is now more generic and is defined by the struct implementing the `HandleMessage` struct.
- ⚡ `GetRequestHandler`, `SubmitOnlyHandler` and `SubmitAndWatchHandler`, e.g. all `WsRpcClient` functions except for the `start_subscriber` are now returning an `Result<Option<String>>` instead of just a `String`. This way, a RpcClientError can be forwarded to the receiving thread. Additionally, a `None` is now allowed, which is quite commonly used in substrate. Most notable result: `send_extrinsic` can now forward the received result and does not depend on the "expected" xt_status any more (making it effectively unable to handle unexpected results, such as Future status).
- `Error::RpcClient()` …
> Future status returns Future error instead of HexError

- .github/release-drafter.yml
- .github/workflows/draft-release.yml
CI generate a draft release upon a new tag that looks like the following: https://github.com/haerdib/substrate-api-client/releases/tag/v0.9.2
- only PR's that include an `E1` or `E2` label are included, `E0` are ignored. To ensure atleast one E label is set, I'm suggesting to introduce a label checker https://github.com/scs/substrate-api-client/issues/324
More Info: https://github.com/release-drafter/release-drafter
> [CI] Add automatic draft release generation

- Cargo.lock
- Cargo.toml
- client-keystore/Cargo.toml
- compose-macros/Cargo.toml
- node-api/Cargo.toml
- primitives/Cargo.toml
- test-no-std/Cargo.toml
Reasoning: The licence header has been changed since v0.1.0. I think that's reason enough for bumping everything
> Bump version of all crates

- Cargo.lock
- Cargo.toml
- client-keystore/Cargo.toml
- compose-macros/Cargo.toml
- node-api/Cargo.toml
- test-no-std/Cargo.toml
- Removes substrate versioning from .tomls
- `cargo update -p sp-std`
closes #338
> Remove substrate versioning and cargo update

- compose-macros/src/lib.rs
- examples/batch_payout.rs
- examples/benchmark_bulk_xt.rs
- examples/compose_extrinsic_offline.rs
- examples/contract_instantiate_with_code.rs
- examples/custom_nonce.rs
- examples/event_error_details.rs
- examples/generic_event_callback.rs
- examples/generic_extrinsic.rs
- examples/get_account_identity.rs
- examples/get_storage.rs
- examples/print_metadata.rs
- examples/staking_payout.rs
- examples/sudo.rs
- examples/transfer_using_seed.rs
- node-api/src/metadata.rs
- src/api/api_client.rs
- src/api/subscription.rs
- src/rpc/mod.rs
- src/rpc/ws_client/client.rs
💥  **Breaking Changes**:  
- `Api` variables are no longer public. They should be accessed via the getter methods
- `get_metadata`, `get_spec_version`, `get_genesis_hash` are now private. The user should access these values via the cached values in the `Api` struct.
❗  Careful: In case one relied on `get_metadata` returning the most recent metadata from the node, that's not the case any more. If that's necessary, run `update_runtime()` before calling the cache via `metadata()`.
- Setter methods (such as `set_signer`) now take a mutable reference and do not return a `Self` anymore.
💚  **Feature Changes**: 
- Added `update_runtime` function to update the Api in case of a runtime upgrade
- removes extra `_get_request` function: RpcClient now directly returns an `Option` without mapping it to …
> [Api] add `update_runtime` function and return metadata from cache

- Cargo.lock
- Cargo.toml
- node-api/Cargo.toml
frame-metadata is now sourced from parity github instead of crates.io (which is very outdated)
closes #286 
closes #304
> Update frame-metdata and remove ed25519-zebra patch

- Cargo.lock
- Cargo.toml
- examples/benchmark_bulk_xt.rs
- examples/compose_extrinsic_offline.rs
- examples/custom_nonce.rs
- examples/event_callback.rs
- examples/event_error_details.rs
- examples/generic_event_callback.rs
- examples/generic_extrinsic.rs
- examples/get_account_identity.rs
- examples/get_blocks.rs
- examples/get_existential_deposit.rs
- examples/get_storage.rs
- examples/print_metadata.rs
- examples/sudo.rs
- examples/transfer_using_seed.rs
- src/api/api_client.rs
- src/api/error.rs
- src/api/mod.rs
- src/api/subscription.rs
- src/rpc/error.rs
- src/rpc/mod.rs
- src/rpc/tungstenite_client/client.rs
- src/rpc/tungstenite_client/mod.rs
- src/rpc/ws_client/client.rs
- src/rpc/ws_client/mod.rs
This PR
-  implement new rpc client with [tungstenite-rs ](https://github.com/snapview/tungstenite-rs)
-  `tungstenite-client` attempt to reconnect to rpc node once disconnected
Run example with tungstenite
```bash
cargo run --no-default-features --features tungstenite-client,std --example get_storage
```
> Support `tungstenite-rs` rpc client

- README.md
Added Polkadex in substrate-api-client readme.
> Added Polkadex in substrate-api-client readme

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- about.toml
- examples/batch_payout.rs
- examples/benchmark_bulk_xt.rs
- examples/compose_extrinsic_offline.rs
- examples/contract_instantiate_with_code.rs
- examples/custom_nonce.rs
- examples/event_callback.rs
- examples/event_error_details.rs
- examples/generic_event_callback.rs
- examples/generic_extrinsic.rs
- examples/get_account_identity.rs
- examples/get_blocks.rs
- examples/get_existential_deposit.rs
- examples/get_storage.rs
- examples/print_metadata.rs
- examples/staking_payout.rs
- examples/sudo.rs
- examples/transfer_using_seed.rs
- examples/transfer_with_tungstenite_client.rs
- examples/transfer_with_ws_client.rs
- src/rpc/error.rs
- src/rpc/jsonrpsee_client/mod.rs
- src/rpc/jsonrpsee_client/subscription.rs
- src/rpc/mod.rs
- src/rpc/tungstenite_client/client.rs
For one run of the example `transfer_using_seed`:
- Without jsonrpsee: 
```
2022-12-06 13:50:54 ✨ Imported #109 (0x5083…7ff3)
2022-12-06 13:50:55 Accepting new connection 1/100
2022-12-06 13:50:55 Accepting new connection 1/100
2022-12-06 13:50:55 Accepting new connection 1/100
2022-12-06 13:50:55 Accepting new connection 1/100
2022-12-06 13:50:55 Accepting new connection 1/100
2022-12-06 13:50:55 Accepting new connection 1/100
2022-12-06 13:50:55 Accepting new connection 1/100
2022-12-06 13:50:57 🙌 Starting consensus session on top of parent 0x50835f1edb77c9e2d5f90336bd7e25c581b9cf6051a39f90425d9cb1f37f7ff3
2022-12-06 13:50:57 🎁 Prepared block for proposing at 110 (0 ms) [hash: 0xa57c1ca6755f5fb5e5a9d2bab7d6e4cbe44049400144a04c38850bd3b0d3cdd7; parent_hash: 0x5083…7ff3; extrinsics (2): …
```
> Add jsonrpsee as default rpc client

- primitives/src/types.rs
- src/api/mod.rs
- src/api/rpc_api/pallet_transaction_payment.rs
- src/api/rpc_api/state.rs
Fixes several bugs noticed in #368:
- adds missing serde skips in primitives types.  These values are not serialized on substrate side, so the deserialization on the api client side needs to skip them as well.
- `XtStatus::Finalized` now matches the number of `TransactionStatus`, which is 6. Otherwise, one would have waited forever until Finalized Status.
- Removes unnecessary enforcement of Decode and Clone on unused `V` of `get_storage_map_proof` and `get_storage_double_map_proof`
> Fix bugs and remove unused Clone / Debug enforcements

- Cargo.lock
- Cargo.toml
- compose-macros/src/lib.rs
- primitives/src/rpc_params.rs
- src/lib.rs
- src/rpc/error.rs
- src/rpc/mod.rs
- src/utils.rs
One step further towards `no_std` compatibility:
- `compsoe-macros` is now fully `no_std` compatible
- `api/rpc` is now fully `no_std` compatible
- remove unused `primitives-types` import in `Cargo.toml`
Drawbacks:
- `thiserror` needed to be changed to `thiserror-core`. But that should be temporary only. And better than removing it completely (I hope).
- Some errors needed to be changed from Error-Types to Strings, because they are not available in `no_std`.
one step towards  https://github.com/scs/substrate-api-client/issues/279
> Make api/rpc interfaces no_std compatible

- Cargo.lock
- primitives/src/pallet_traits/pallet_staking_config.rs
Substrate update:
- Rename `SlashCancelOrigin` to `AdminOrigin`  (see https://github.com/paritytech/substrate/commit/c16472e7e4a588d8e202c1ab3e865cf6e7b201c5) 
Plus a general `cargo update`
> Update to the newest substrate commit + cargo update

- Cargo.lock
- Cargo.toml
- compose-macros/Cargo.toml
- node-api/Cargo.toml
- primitives/Cargo.toml
I think it's time for the next tag `v0.9.0` :)
Lots happened, such as Trait introduction for the RpcClient and Api Client, almost full `no_std` support, introduction of jsonrpsee client and tungsenite client, new features, and so on.
Changes from now to tag v0.8.0 can be looked up here: https://github.com/scs/substrate-api-client/compare/v0.8.0...master#
Summary:
- `ac-compose-macros` has new features (full no_std and rpc_params), no breaking changes.
- `ac-examples` got newly created
- `ac-node-api` implements new functions (such as `check_if_failed`), no breaking changes.
- `ac-primitives`: removed of `hex_encode` function as well as enforcing Serializing in no_std. Therefore, breaking changes were introduced.
- `api-client` : Lots of breaking changes.
> Update .toml version

- README.md
- examples/examples/benchmark_bulk_xt.rs
- examples/examples/compose_extrinsic_offline.rs
- examples/examples/custom_nonce.rs
- examples/examples/sudo.rs
I mostly wanted to fix the `cargo run` command for the examples, but I also fixed some minor typos along the way
> Fix documentation for running an example.

- Cargo.lock
- Cargo.toml
- src/api/api_client.rs
- src/api/error.rs
- src/rpc/error.rs
- src/rpc/tungstenite_client/client.rs
- src/rpc/ws_client/client.rs
- src/rpc/ws_client/mod.rs
- remove this error and replace with `derive_more` where possible. This should declutter some overly verbose error messages. Better for `no_std` environments.
- clean up some unused error values
- remove generic Result in ws client - not used anyway and makes it more complex than necessary
closes #317
> Remove thiserror

- examples/examples/batch_payout.rs
- examples/examples/benchmark_bulk_xt.rs
- examples/examples/compose_extrinsic_offline.rs
- examples/examples/contract_instantiate_with_code.rs
- examples/examples/custom_nonce.rs
- examples/examples/event_error_details.rs
- examples/examples/get_account_identity.rs
- examples/examples/sudo.rs
- examples/examples/transfer_with_tungstenite_client.rs
- examples/examples/transfer_with_ws_client.rs
- src/api/rpc_api/author.rs
- testing/examples/author_tests.rs
Renames current extrinsic submission to `opaque` and add new, more restrictive `submit_extrinisc` and similiar functions instead. This way, the encoding does not have to be implemented on client side and is less error prone as UncheckedExtrinsicV4 type is enforced.
closes #90
> Enforce `UncheckedExtrinsicV4` for `submit_extrinsic` and add `_opaque_extrinsic`

- examples/examples/custom_nonce.rs
- node-api/src/lib.rs
- src/api/error.rs
- src/api/mod.rs
- src/api/rpc_api/author.rs
- removes unused Api Error
- use clearer naming for the Api Error
- UnexptedTxStatus Error contains a clearly defined Enum, not a String. This should be easier to check for a specific status (e.g. Future), than with the previously used string.
- Removed `FinalityTimeout` from expected. Reasoning: If one waits for `Finalized`, but a Timeout is encountered, the loop would go on forever.
> Clean up Api Error and indicate future status clearly

- compose-macros/src/lib.rs
- examples/examples/batch_payout.rs
- examples/examples/benchmark_bulk_xt.rs
- examples/examples/compose_extrinsic_offline.rs
- examples/examples/contract_instantiate_with_code.rs
- examples/examples/custom_nonce.rs
- examples/examples/event_callback.rs
- examples/examples/event_error_details.rs
- examples/examples/get_account_identity.rs
- examples/examples/get_storage.rs
- examples/examples/sudo.rs
- examples/examples/transfer_with_tungstenite_client.rs
- examples/examples/transfer_with_ws_client.rs
- primitives/src/extrinsics.rs
- primitives/src/lib.rs
- primitives/src/signer.rs
- src/api/api_client.rs
- src/api/rpc_api/author.rs
- src/api/rpc_api/frame_system.rs
- src/extrinsic/balances.rs
- src/extrinsic/common.rs
- src/extrinsic/contracts.rs
- src/extrinsic/offline_extrinsic.rs
- src/extrinsic/staking.rs
- src/extrinsic/utility.rs
- testing/examples/author_tests.rs
- testing/examples/frame_system_tests.rs
- testing/examples/pallet_transaction_payment_tests.rs
`UncheckedExtrinsic` is now generic over the AccountId, Signer and Address type. All types of substrate nodes should now be supported, no matter which Account types are used.
- introduced `SignExtrinsic` trait to simplify the `Address`, `AccountId` and `Signature` allocation as much as possible.
- The default implementation `ExtrinsicSigner` should be usable for most use cases, except for when no `Runtime` is used. In that case one still has to option to implement the trait oneselves.
- `UncheckedExtrinsic` now implements a `new_unsigned` function.
Drawback: `Signature` type needs to be defined explicitly. However, https://github.com/scs/substrate-api-client/issues/406 may help with that.
closes #360
> Make UncheckedExtrinsicV4 generic

- README.md
> Add `no_std` rpc client to readme

- examples/examples/event_callback.rs
- node-api/src/lib.rs
- src/api/rpc_api/events.rs
- src/api/rpc_api/frame_system.rs
- testing/examples/events_tests.rs
- testing/examples/frame_system_tests.rs
Removes the obsolete `wait_for_event` functions. I don't see the use case of these functions any more.
In addition, the event subscription has been updated:
- Renames `subscribe_frame_events` to `subscribe_events` and moved to more fitting `event.rs` instead of the frame_system file.
- Instead of returning the `StorageChangeSet`, which required quite some type insight to retrieve the events from it, a struct `EventSubscription` is returned. Upon `next_event` it directly tries to retrieve the events.
closes #413
> Remove `wait_for_event` and simplify event access in `subscribe_events`

- src/api/rpc_api/frame_system.rs
> `GetAccountInformation` has no contraint on `Signer`

- primitives/src/serde_impls.rs
- src/api/rpc_api/pallet_balances.rs
- impl From<Vec<u8>> for StorageKey: https://github.com/scs/substrate-api-client/issues/455
- Remove <Hash> from Balance Trait: https://github.com/scs/substrate-api-client/issues/465
> impl From<Vec<u8>> for StorageKey and remove <Hash> from Balance Trait

- Cargo.lock
- client-keystore/src/lib.rs
- examples/examples/benchmark_bulk_xt.rs
- examples/examples/compose_extrinsic_offline.rs
- examples/examples/custom_nonce.rs
- examples/examples/event_error_details.rs
- examples/examples/sudo.rs
- examples/examples/transfer_with_tungstenite_client.rs
- examples/examples/transfer_with_ws_client.rs
- primitives/src/pallet_traits/pallet_balances_config.rs
- src/api/rpc_api/events.rs
- src/extrinsic/balances.rs
- testing/examples/author_tests.rs
- testing/examples/events_tests.rs
- testing/examples/pallet_transaction_payment_tests.rs
- Upgrade to substrate commit : https://github.com/paritytech/substrate/tree/8bd57418b79d2450079755c0d631168b8fad2e97
- Change Keystore according to https://github.com/paritytech/substrate/commit/bf395c8308c481a9774373e0b0b14bd7a2e4b8d2 and https://github.com/paritytech/substrate/commit/9d2d020c5134d8c7870396cb04bca63a674abfd5
- Change Balances because of https://github.com/paritytech/substrate/pull/12951. Note that
- free, locked and reserved balances are defined differently  
- Existential Deposit requirements to be made of the free balance, not the total balance
- set_balance is new force_set_balance
- transfer is transfer_allow_death
- Cargo update
- Fix the tests but the [DispatchError](https://github.com/scs/substrate-api-client/blob/33622f4d3e6a949e1a6efa507cff58173d74d856/node-api/ …
> update to newest substrate

- node-api/src/lib.rs
> Add Debug to EventRecord

- Cargo.lock
- primitives/Cargo.toml
- primitives/src/extrinsics/signer.rs
closes #461
workaround for #504
> Add static signer

- rustfmt.toml
Explicitly state the edition as CLion is somehow not able to correctly pick up the edition when using rustfmt. 
I guess rustfmt is not being executed with `cargo` and then it defaults to `2015`:
https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#edition
Then CLion constantly complains when using newer features such as `async`...
> Explicitly state edition in rustfmt.toml

- Cargo.lock
- Cargo.toml
- client-keystore/Cargo.toml
- compose-macros/Cargo.toml
- examples/Cargo.toml
- node-api/Cargo.toml
- primitives/Cargo.toml
- testing/Cargo.toml
Changes can be looked up here: https://github.com/scs/substrate-api-client/compare/v0.10.0...v0.11.0
Summary:
- `api-client`: ⚡  Contains breaking changes due to function renaming and pub re-exports removals.
- `client-keystore`:  ⚡  Breaking changes due to substrate update
- `compose-macros`:  ⚡  Breaking changes due to `pub use rpc::*` removal
- `examples`:  ⚡  follow the breaking changes of substrate
- `node-api`:  ⚡  breaking changes due to more restrictive public re-export
- `primitives`: ⚡  breaking changes due to more restrictive public re-export and file moving
- `testing`: ⚡  follow the breaking changes of substrate
> Udpate toml versions for tag v0.11.0

- README.md
> Add example upgrade section to readme

- examples/examples/print_metadata.rs
- node-api/src/metadata.rs
To make it more obvious to the user what's the difference between `Metadata` and `metadata` the following is updated:
- renamed `metadata` to `runtime_metadata`
- Added explanatory comment to `Metadata`struct
- `pretty_format` now takes self as argument and returns an error instead of an Option (which resulted in information loss in case of an error)
closes #493
> Clarify distinction of `Metadata` struct and internal `metadata` field

- examples/examples/compose_extrinsic_offline.rs
- examples/examples/custom_nonce.rs
- examples/examples/get_blocks.rs
- src/api/mod.rs
- src/api/rpc_api/author.rs
- src/api/rpc_api/chain.rs
- src/api/rpc_api/events.rs
- testing/examples/chain_tests.rs
- testing/examples/events_tests.rs
- testing/examples/pallet_transaction_payment_tests.rs
- testing/examples/state_tests.rs
- In order to use `get_finalized_head()` inside of `get_finalized_block()` I had to add a trait bound for `Runtime::Header` but I think it is not too limiting.
- There is already a `genesis_hash()` in `API`. I implemented `get_genesis_block()` instead.
- Merged the `GetBlock` and `GetHeader` traits into a single `GetChainInfo` trait
> Expand chain api

- examples/examples/event_callback.rs
- node-api/src/events.rs
- src/api/rpc_api/events.rs
- testing/examples/events_tests.rs
Updated the `EventSubscription` Wrapper to support decoding events from the metadata:
- added new functionality `next_events_from_metadata` to derive events from metadata instead of `RuntimeEvents` generated by the `construct_runtime` macro of Substrate
- renamed `next_event` to more appropriate `next_events`.
- introduced a `metadata` field for event derivation from metadata (needed by `next_events_from_metadata`). Therefore, the `From` derivation from `Subscription`is not possible any more (needs metadata) and was removed.
closes https://github.com/scs/substrate-api-client/issues/440
> Add `next_events_from_metadata` and rename `next_event`

- .github/workflows/ci.yml
Fixes the Node.js warnings (see Annotations here: https://github.com/scs/substrate-api-client/actions/runs/4806291597?pr=541)
> Bump cargo-install to remove Node.js warnings

- Cargo.lock
- Cargo.toml
- client-keystore/Cargo.toml
- compose-macros/Cargo.toml
- examples/Cargo.toml
- node-api/Cargo.toml
- primitives/Cargo.toml
- test-no-std/Cargo.toml
- testing/Cargo.toml
Changes can be looked up here: https://github.com/scs/substrate-api-client/compare/v0.11.0...master
Summary:
- `api-client`: ⚡  Contains breaking changes due to clean trait bounds and new functionalities
- `client-keystore`: ⚡  breaking changes due to to substrate update 
- `compose-macros`:  ⚡  breaking changes due to async support
- `examples`:  ⚡  breaking changes due to clean trait bounds and new functionalies
- `node-api`:  ⚡  breaking changes due to improve of metadata and dispatch errors
- `primitives`: ⚡  breaking changes due to clean trait bounds
- `testing`: ⚡  breaking changes due to async support
> Update toml versions for tag v0.12.0

- primitives/src/config/mod.rs
- src/api/rpc_api/frame_system.rs
- testing/examples/frame_system_tests.rs
Fixes #572
Regarding the `// FIXME: Remove once #391 is fixed.` : Issue added in #574
> Add function `get_system_account_next_index`

- src/api/rpc_api/frame_system.rs
Only realized after merging #573 , but I believe `get_system_account_next_index` fits better to `GetAccountInformation`. This way, `index` and `AccountId` do not need to be redefined for trait `SystemApi`.
> Move `get_system_account_next_index` to `GetAccountInformation`

- Cargo.lock
- client-keystore/src/lib.rs
- examples/examples/get_blocks_async.rs
- examples/examples/get_storage.rs
- rust-toolchain.toml
- run `cargo update`
- updated rust toolchain to `nightly-2023-05-22`
- updated keystore according to Substrate changes
- removed some clippy warnings due to unused dependencies
- fixed comment and added Balance type to example `get_storage`
closes #577
> Update dependencies and rust toolchain

- Cargo.lock
- Cargo.toml
- node-api/Cargo.toml
- node-api/src/events.rs
- node-api/src/from_v14_to_v15.rs
- node-api/src/lib.rs
- node-api/src/metadata.rs
- node-api/src/storage.rs
- node-api/src/test_utils.rs
- src/api/rpc_api/events.rs
Support metadata v15. Any metadata v14 is converted to v15.
closes #544
> support metadata v15

- src/api/rpc_api/frame_system.rs
removed std feature flag for `get_system_account_next_index`
closes #574
> Make `get_system_account_next_index` available for `no_std`

- Cargo.lock
- compose-macros/src/lib.rs
- node-api/Cargo.toml
- node-api/src/error/dispatch_error.rs
- node-api/src/error/mod.rs
- node-api/src/events/event_details.rs
- node-api/src/events/mod.rs
- node-api/src/lib.rs
- node-api/src/metadata/error.rs
- node-api/src/metadata/metadata_types.rs
- node-api/src/metadata/mod.rs
- node-api/src/metadata/print_metadata.rs
- node-api/src/metadata/variant_index.rs
- node-api/src/scale_value/decode.rs
- node-api/src/scale_value/mod.rs
- node-api/src/test_utils.rs
- src/api/api_client.rs
- src/api/mod.rs
- src/api/rpc_api/author.rs
- src/api/rpc_api/events.rs
- src/api/rpc_api/state.rs
- testing/examples/author_tests.rs
- testing/examples/events_tests.rs
- testing/examples/frame_system_tests.rs
Updates the Metadata, Error and Event to use the new visitor decoding. The following was updated:
- Renamed `ModuleErrorData` to `RawModuleError`. This seems more appropriate. 
- Updated `decode_from` to use the visitor pattern and less verbose code structure.
- `EventDetails` are now generic over the Hash because `topics` are now used internally
- `EventDetails::decode_from` was changed to use the visitor pattern.
- Introduced `EventMetadataDetails` struct as helper for retrieving pallet specific event variants.
- Removed `pub` access from underlying variables of the `Metadata` struct. Reasoning: Modifying single attributes does not make sense because all parameters are derived from the underlying `runtime_metadata`. So to change one parameter, the runtime_metadata should be updated and …
> Update Metadata, Error and Events

- Cargo.lock
- Cargo.toml
- client-keystore/Cargo.toml
- compose-macros/Cargo.toml
- examples/Cargo.toml
- node-api/Cargo.toml
- primitives/Cargo.toml
- testing/Cargo.toml
Changes can be looked up here: https://github.com/scs/substrate-api-client/compare/v0.12.0...master
Summary:
- `api-client`: ⚡  Contains breaking changes due to node-api update.
- `client-keystore`:  no breaking changes, new functionality only
- `compose-macros`:  no breaking changes. Updates are internal only due to node-api update
- `examples`:  no breaking changes
- `node-api`:  ⚡   lots of breaking changes: see https://github.com/scs/substrate-api-client/pull/597
- `primitives`: ⚡  breaking changes due to removal of duplicate types: https://github.com/scs/substrate-api-client/pull/580
- `testing`: no breaking changes
closes #595
> Prepare for tag v0.13.0

- src/api/rpc_api/author.rs
- src/api/rpc_api/pallet_transaction_payment.rs
- testing/examples/pallet_transaction_payment_tests.rs
Take `Bytes` parameters by reference. Makes the code a bit more idiomatic and efficient.
We mostly use it for serialization and this works fine as it is also implemented for the reference.
> Take Bytes parameters as borrow

- examples/examples/get_storage.rs
- src/api/rpc_api/state.rs
- testing/examples/state_tests.rs
Add **get_all_storage_keys_paged_up_to_count** to fetch required number of keys, independantly of substrate limit:
- call several times the substrate RPC call with the max limited number (1000), if required
The default call, **get_storage_keys_paged** performs according to substrate: if required number of keys> 1000, an error is thrown. The documentation warns the user.
This does not completely fix #588. To fetch all pages, you need to know how many keys are stored. Currently,  `count `is mandatory in [`state_getKeysPaged`](https://github.com/paritytech/substrate/blob/fe2d51377fe1a8fbbb0599523f4fdc1422c82f81/client/rpc/src/state/mod.rs#L374) and substrate doesn't support the feature for obtaining all keys.
> fetch more storage keys than the maximum limit set by substrate

- examples/examples/compose_extrinsic_offline.rs
- examples/examples/contract_instantiate_with_code.rs
- examples/examples/custom_nonce.rs
- examples/examples/event_error_details.rs
- examples/examples/get_account_identity.rs
- examples/examples/staking_batch_payout.rs
- examples/examples/sudo.rs
- examples/examples/transfer_with_tungstenite_client.rs
- examples/examples/transfer_with_ws_client.rs
- src/api/mod.rs
- src/api/rpc_api/author.rs
- testing/examples/author_tests.rs
- testing/examples/dispatch_errors_tests.rs
- testing/examples/events_tests.rs
Rename functions to clarify that events are not always listed in the extrinisc report:
- Light version: `submit_and_watch_extrinsic_until_without_events`: submit and watch the extrinsic until the desired status is reached. No events are fetched, so no events are listed in the report. 
- `submit_and_watch_extrinsic_until`: submit and watch the extrinsic until the desired status is reached. When the extrinisc is InBlock or Finalized, the events are retrieved and added in the report.
**Caution**: The previous function `submit_and_watch_extrinsic_until_success ` is deprecated, but `submit_and_watch_extrinsic_until` has different behaviour. Previously it didn't fetch the events. Now it does so for InBlock and Finalized status
Closes https://github.com/scs/substrate-api-client/issues/592
> Rework submit and watch extrinsics

- examples/examples/check_extrinsic_events.rs
- src/api/rpc_api/author.rs
- src/api/rpc_api/events.rs
- testing/examples/author_tests.rs
The problem was that we encoded the extrinsic twice: `T::Hasher::hash_of(..) ` encodes the input automatically. We therefore need to use `T::Hasher::hash(..) ` for the already encoded extrinsic.
The extrinsic hash can be manually checked by:
- run a local node `docker run -p 9944:9944 -p 9933:9933 -p 30333:30333 parity/substrate:latest --dev --rpc-external`
- run example printing xt_hash: `cargo run -p ac-examples --example check_extrinsic_events`
- compare printed extrinsic hash with the one on polkadot.js (https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/explorer)
closes https://github.com/scs/substrate-api-client/issues/621
> Fix reported extrinsic hash

- Cargo.lock
- Cargo.toml
- examples/Cargo.toml
- node-api/Cargo.toml
- primitives/Cargo.toml
- primitives/src/extrinsics/mod.rs
- src/rpc/jsonrpsee_client/mod.rs
- testing/Cargo.toml
to substrate commit [#d38d176b844aab1338ce79eb71cd6df86c97d4a0](https://github.com/paritytech/substrate/commit/d38d176b844aab1338ce79eb71cd6df86c97d4a0)
Add changes to compile:
- cargo update -p x25519-dalek --precise 2.0.0-pre.1 because of https://github.com/paritytech/substrate/commit/8463ca3f2ce53b3dcbe9c3b382d946934e1f37c9
- from commit https://github.com/paritytech/substrate/commit/e00031e481c381d0622e2e366247fadd20ec1ac5: Extract address,call,sig,extra ty from tx type
> bump substrate

- Cargo.lock
- Cargo.toml
- compose-macros/Cargo.toml
- examples/Cargo.toml
- node-api/Cargo.toml
- primitives/Cargo.toml
- testing/Cargo.toml
Changes can be looked up here: https://github.com/scs/substrate-api-client/compare/v0.13.0...master
Summary:
- `api-client`: ⚡  Contains breaking changes due to primitives update.
- `client-keystore`:  nothing changed since v0.13.0
- `compose-macros`:  no breaking changes.
- `examples`:  no breaking changes
- `node-api`:  no breaking changes
- `primitives`: ⚡  breaking changes due to renaming of Config: https://github.com/scs/substrate-api-client/pull/604
- `testing`: no breaking changes
related to #634
> Prepare for tag v0.14.0

- README.md
README still contained --ws-external as argument, which isn't used anymore. See also #565
> update substrate cmd args in README

- Cargo.lock
- Cargo.toml
- client-keystore/Cargo.toml
- examples/Cargo.toml
- node-api/Cargo.toml
- primitives/Cargo.toml
- test-no-std/Cargo.toml
- testing/Cargo.toml
> Switch to using the new polkadot-sdk

- primitives/src/config/mod.rs
Seems like reasonable assumptions for me, and they made my code in the worker a bit more ergonomic. :)
* Closes #646
> Add trait bounds to config: `Index: Default`, `BlockNumber: AtLeast32BitsUnsigned`

- .github/workflows/ci.yml
- examples/examples/transfer_with_tungstenite_client.rs
- examples/examples/transfer_with_ws_client.rs
- src/rpc/error.rs
- src/rpc/helpers.rs
- src/rpc/mod.rs
- src/rpc/tungstenite_client/client.rs
- src/rpc/tungstenite_client/subscription.rs
- src/rpc/ws_client/client.rs
- src/rpc/ws_client/mod.rs
- src/rpc/ws_client/subscription.rs
- testing/examples/tungstenite_client_test.rs
- testing/examples/ws_client_test.rs
Updates the ws-rpc and tungstenite clients with the following features:
- Removal of the warning message "Expected subscription, but received an ID response instead: Object"
- The immediate subscription response (either the subscription ID or an error) is now interpreted by the client. All the following subscription messages are checked by the client if the ID matches, and only then are forwarded to the client. This now removes the need to ignore the "id" response that previously generated the responses, and does not allow mix-up of different subscription messages.
- adds tests to the CI to test the following three cases:
-  Failed onchain extrinsic (Extrinsic went through successfully, only the Events indicate a failure of the xt)
- Failed extrinsic before block submission (E.g. no …
> Add subscription ID recognition to tungstenite and ws-rpc client

- src/rpc/tungstenite_client/client.rs
- src/rpc/ws_client/mod.rs
Changes the log level of tungstenite and ws-rpc client to lower level or even remove them due to duplicity. This will help the users to reduce potential clustering of log levels, since especially metadata retrieval results in enormous log messages.
closes #623
> Lower log-level of messages of tungstenite and ws-rpc clients

- .github/release-drafter.yml
- .github/workflows/check-lables.yml
- CI now checks for F-Labels
- Updates release generation to check for more labels
To ensure F-lables can always be set, I introduced the additional F-Labels:
`F0-miscellaneous`
`F9-dependencies`
closes #641
> Enforce F-label on PRs by CI

- src/api/rpc_api/author.rs
> Rpc-api author: Clarify comments about blocking functions

- Cargo.lock
- about.toml
- examples/examples/get_account_identity.rs
- Update to polkadot sdk commit [ `fcfdb98` ](https://github.com/paritytech/polkadot-sdk/commit/fcfdb98ab5c5fce91cce339c8d3e4f5f5844bbe1) (release-polkadot-v1.4.0)
- update identity pallet example
-  Allow GPL-3.0 licence for now (see #696)
> Update to polkadot release v1.4.0 commit

- .github/workflows/ci.yml
- node-api/src/error/mod.rs
Clippy warned about too large error in node-api, once it was actually run there. Therefore, this PR updates:
- CI : Now also tests node-api with  clippy
- Adds Box around Decode and EncodeError to constrain the error.
> node-api: Box Error::DecodeValue and Error::EncodeValue

- Cargo.lock
- Cargo.toml
- src/rpc/jsonrpsee_client/mod.rs
> Update jsonrpsee to v0.21

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- README.md
- examples/async/examples/query_runtime_api.rs
- primitives/src/types.rs
- src/api/api_client.rs
- src/api/mod.rs
- src/api/runtime_api/account_nonce.rs
- src/api/runtime_api/api_core.rs
- src/api/runtime_api/authority_discovery.rs
- src/api/runtime_api/block_builder.rs
- src/api/runtime_api/metadata.rs
- src/api/runtime_api/mmr.rs
- src/api/runtime_api/mod.rs
- src/api/runtime_api/session_keys.rs
- src/api/runtime_api/staking.rs
- src/api/runtime_api/transaction_payment.rs
- src/api/runtime_api/transaction_payment_call.rs
- testing/async/examples/runtime_api_tests.rs
Adds general runtime api support  via rpc call `state_call`:
- add a RuntimeApi struct for a clean, separate runtime api interface. Otherwise, there would be overlapping function names.
- add functions for commonly available runtime calls (full list can be viewed here: https://polkadot.js.org/docs/polkadot/runtime)
- add system test to the testing examples where possible
- add an example to show how to access the runtime api.
closes #520
> Add Runtime Api support

- Cargo.lock
- compose-macros/Cargo.toml
- compose-macros/src/lib.rs
- src/api/api_client.rs
> Split compose_call into two functions

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/api/api_client.rs
- src/api/rpc_api/events.rs
With the `--all-features` the async version of the unit tests is not needed anymore.
Reasoning: Previously, `cargo test --release` has built the api-client in default mode, which is async. With the newly added `--workspace` the client is now built in sync mode. 
I believe that's reasonable, as we already test the async version thoroughly in the system tests.
> CI: Ensure unit tests are run in all crates

- .github/workflows/ci.yml
- examples/async/examples/check_extrinsic_events.rs
- node-api/src/error/dispatch_error.rs
- node-api/src/events/event_details.rs
- node-api/src/events/mod.rs
- node-api/src/events/raw_event_details.rs
- node-api/src/lib.rs
- node-api/src/metadata/error.rs
- src/api/api_client.rs
- src/api/mod.rs
- src/api/rpc_api/author.rs
- src/api/rpc_api/events.rs
- src/api/rpc_api/runtime_update.rs
- testing/async/examples/author_tests.rs
- Removed Pointer and usize from `EventDetails` as they do not implement codec Decoding / Encoding.
- Added `RawEventDetails` to allow usage of EventDetails without always holding the full metadata
- Changed `ExtrinsicReport` to use `RawEventDetails` instead, to make the report smaller. Otherwise, the full metadata would get encoded / decode and moved all the time. I'd rather keep the report small. If needed, one can always transform the `RawEventDetails` back to `EventDetails`
closes  #397
> Add Encode Decode to ExtrsinicReport and use RawExtrinsicDetails

- .github/workflows/ci.yml
- README.md
Updated GitHub Actions to use the most up-to-date actions.
Please note: GitHub actions artifacts are immutable once uploaded in v4. Therefore, every upload needs a unique name. To still have one upload artifact at the end the step `merge` was introduced. This ensures that users can still download all examples as one zip.
See https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md for more information
closes #723
> CI: update github actions

- src/api/error.rs
- src/api/rpc_api/author.rs
- testing/async/examples/dispatch_errors_tests.rs
When an extrinsic fails onchain, the full encoded report is now returned. This allows the user to retrieve the associated events, blockhash and the dispatch error.
> Add failed extrinsic error

- Cargo.lock
- Cargo.toml
- src/rpc/jsonrpsee_client/mod.rs
- testing/async/Cargo.toml
- testing/async/examples/jsonrpsee_tests.rs
- Updates jsonrpsee to v22
- Add function `new_with_client` and forwards the inner functionalities of the client, incl. the relevant system tests.
closes #714
> Add Jsonrpsee::new_with_client

- Cargo.lock
- node-api/src/lib.rs
- src/api/error.rs
- src/lib.rs
- src/rpc/error.rs
> make stable work for std build

- Cargo.toml
- compose-macros/Cargo.toml
- examples/async/Cargo.toml
- examples/sync/Cargo.toml
- node-api/Cargo.toml
- test-no-std/Cargo.toml
- testing/async/Cargo.toml
- testing/sync/Cargo.toml
It is allowed to have the local path as well as the version number in the dependencies. For local builds the path is used (but the version number is still verified) and on crates.io the version number is used. 
See also this description:
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations
This should make releases in the future simpler as we don't have to add the version numbers later. See for example this branch that adds the version numbers:
https://github.com/scs/substrate-api-client/pull/742
> Add the crates.io version numbers for local dependencies

- Cargo.lock
- primitives/Cargo.toml
- primitives/src/extrinsics/mod.rs
- primitives/src/extrinsics/signer.rs
Currently our dependencies are broken on master. For example `cargo update` fails with:
```
Updating crates.io index
Updating git repository `https://github.com/paritytech/polkadot-sdk.git`
error: no matching package named `node-template-runtime` found
location searched: https://github.com/paritytech/polkadot-sdk.git?branch=master
required by package `ac-primitives v0.9.1 (/home/tniederberger/repos/substrate-api-client/primitives)`
```
Apparently the node-template-runtime dependency has been renamed to solochain-template-runtime. See this PR: https://github.com/paritytech/polkadot-sdk/pull/3460
and especially this line https://github.com/paritytech/polkadot-sdk/blob/4c810609d6c72b48bd748398165da5c27a604778/prdoc/pr_3460.prdoc#L24
Additionaly it seems that `SignedExtra` has been renamed to …
> Rename node-template-runtime dependency

- Cargo.lock
This should fix the security advisory:
https://github.com/scs/substrate-api-client/security/dependabot/27
> Update mio dependency that has a vulnerability

- Cargo.toml
- compose-macros/README.md
- keystore/Cargo.toml
- keystore/README.md
Variety of small improvements for the Cargo.toml files and README.md
> Update and improve crate-metadata

- rust-toolchain.toml
I'm currently looking a bit into the WebAssembly compatibility and there were quite a few changes recently. So I would like to update to the newest nightly.
> Update rust version to newest nightly

- .github/workflows/ci.yml
- Cargo.lock
- primitives/src/extrinsics/mod.rs
- rust-toolchain.toml
I realized that with the current polkadot version we can support additional features for WebAssembly 🥳 
Run a cargo update and add test for new wasm target/features.
I also had to revert changes related `TxExtension`. There is currently a back and forth regarding this in polkadot:
- PR https://github.com/paritytech/polkadot-sdk/pull/2280
- Revert of the PR: https://github.com/paritytech/polkadot-sdk/pull/3665
- Revert of the revert: https://github.com/paritytech/polkadot-sdk/pull/3685
> Better wasm support

- .github/workflows/ci.yml
Build should run once per day and also do a `cargo update` in order to make sure the api-client still builds against the latest polkadot master
> Create a nightly build

- .github/workflows/ci.yml
A small improvement to our build such that we also upload the Cargo.lock. This is mostly useful for the nightly build which updates the Cargo.lock but since it is a small file we can include it in all the builds.
> Upload Cargo.lock during build

- .github/workflows/ci.yml
This docker image is only a couple of days newer than paritypr/substrate:latest but the build passes and we know which hash of polkadot-sdk it belongs to.
> Find working docker image

- .github/workflows/ci.yml
- examples/async/examples/unstable_rpc_api_calls.rs
This is a quick fix to get the test working again. I created a follow up issue to provide an actual API for the functionality in the `unstable_rpc_api_calls.rs` test. See https://github.com/scs/substrate-api-client/issues/779
In this PR:
- Use stabilized versions of chainSpec calls
- Use newer docker image (From 01.11.2023)
> Use stabilized chainSpec calls in `unstable_rpc_api_calls`

- .github/workflows/ci.yml
- testing/async/examples/state_tests.rs
Add debug output
Docker images:
- master-00b85c51 broken (01.11.2023)
- master-f50054cf working (01.11.2023)
It seems it is broken since this commit: https://github.com/paritytech/polkadot-sdk/commit/00b85c51dfbc0fecbb8a4dd3635d4c177a6527a6
According to this PR `ErasStakers` has been deprecated:
https://github.com/paritytech/polkadot-sdk/commit/00b85c51dfbc0fecbb8a4dd3635d4c177a6527a6
> Fix the state_tests

- .github/workflows/ci.yml
- examples/async/examples/unstable_rpc_api_calls.rs
- Use stabilized transaction calls
- Again just the minimal change to get the test working. For proper integration see #779 
- Corresponding polkadot branch: https://github.com/paritytech/polkadot-sdk/pull/4171
- Use newer docker image
- The docker image is no special version. Just old enough that it does not yet contain the merkelized metadata (See #777)
> Use stabilized transaction calls

- Cargo.lock
- Cargo.toml
- compose-macros/Cargo.toml
- examples/async/Cargo.toml
- examples/sync/Cargo.toml
- examples/wasm/Cargo.toml
- keystore/Cargo.toml
- node-api/Cargo.toml
- primitives/Cargo.toml
- test-no-std/Cargo.toml
- testing/async/Cargo.toml
- testing/sync/Cargo.toml
Preparation for release on crates.io. Moved all version numbers to 0.18.0
> Switch all internal version numbers to 0.18.0

- .github/workflows/ci.yml
Recently our builds failed multiple times due to lack of disk space (`No space left on device`). For example here: https://github.com/scs/substrate-api-client/actions/runs/10171581409
I suspect this has become a problem because we added compilation to WebAssembly to the build a while ago.
Solution:
Remove some pre-installed tools from the runner that we don't need
> Fix disk issues with Github runners

- .github/workflows/ci.yml
- examples/async/examples/new_json_rpc_api_calls.rs
The calls in the example are not unstable anymore so the name does not make sense anymore
- Change the file name as the calls are not unstable anymore
- Given that the calls are stable we don't need to verify that they exist
Also see comments in issue #779
> Transform "unstable" example into an "new JSON-RPC" example

- compose-macros/src/lib.rs
- node-api/src/lib.rs
- primitives/src/config/mod.rs
- primitives/src/types.rs
- rust-toolchain.toml
- src/api/error.rs
- src/lib.rs
- src/rpc/error.rs
- test-no-std/src/main.rs
This PR updates the following:
- Removes `error_in_core` feature, as this has been integrated in the toolchain.
- updates rust toolchain
- fixes clippy lints, such as https://rust-lang.github.io/rust-clippy/master/index.html#/too_long_first_doc_paragraph  and https://rust-lang.github.io/rust-clippy/master/index.html#/doc_lazy_continuation
closes #799
> Update rust toolchain

- src/api/error.rs
- src/api/mod.rs
- src/api/rpc_api/author.rs
- testing/async/examples/author_tests.rs
- Move Retracted enum value from `UnexpectedTxStatus` to `XtStatus`
- Provide is_final method for `TransactionStatus`
- Currently not used, but I think it makes sense to provide it
- Return from watch method as soon as a final state is reached
- Provide separate method to populate events for an `ExtrinsicReport`
- I think separating it makes sense but I'm not sure we want to add it to the trait
- See also #773
> Implement state handling for Retracted status

- README.md
- docs/README.md
I tried to come up with some documentation regarding the new versioning strategy and to make our release approach more explicit.
> Add documentation for version numbering and releases

- about.toml
ring licensing (3 in one file) confuses the cargo-about, so a workaround was added: https://embarkstudios.github.io/cargo-about/cli/generate/config.html
closes #814
> Add Unicode-3.0 to accpeted licences

- .github/workflows/ci.yml
- Cargo.lock
- examples/async/examples/benchmark_bulk_xt.rs
- examples/async/examples/check_extrinsic_events.rs
- examples/async/examples/compose_extrinsic.rs
- examples/async/examples/custom_nonce.rs
- examples/async/examples/get_storage.rs
- examples/async/examples/new_json_rpc_api_calls.rs
- examples/async/examples/query_runtime_api.rs
- examples/async/examples/runtime_update_async.rs
- examples/async/examples/staking_batch_payout_untested.rs
- examples/async/examples/sudo.rs
- examples/sync/examples/runtime_update_sync.rs
- node-api/src/events/raw_event_details.rs
- primitives/src/extrinsics/mod.rs
- primitives/src/extrinsics/signer.rs
- rust-toolchain.toml
- testing/async/examples/author_tests.rs
- testing/async/examples/chain_tests.rs
- testing/async/examples/dispatch_errors_tests.rs
- testing/async/examples/events_tests.rs
- testing/async/examples/frame_system_tests.rs
- testing/async/examples/pallet_balances_tests.rs
- testing/async/examples/pallet_transaction_payment_tests.rs
- testing/async/examples/runtime_api_tests.rs
- testing/async/examples/state_tests.rs
- Downgrade CI image to Ubuntu 22.04 due to https://github.com/scs/substrate-api-client/issues/817
- cargo update to commit right before introduction of ExtrinsicV5
- Replace `AccountKeyring` with `Sr25519Keyring` (see https://github.com/paritytech/polkadot-sdk/pull/5899)
- Fix runtime api metadata tests  (see https://github.com/paritytech/polkadot-sdk/pull/5732 for more Infos)
- Fix clippy lints `elided lifetime`
part of  #812
> Cargo update

- Cargo.toml
- examples/async/Cargo.toml
- examples/sync/Cargo.toml
- primitives/Cargo.toml
- primitives/src/extrinsics/extrinsic_params.rs
- primitives/src/extrinsics/extrinsic_params_without_hash_check.rs
- primitives/src/extrinsics/mod.rs
- testing/async/Cargo.toml
- testing/sync/Cargo.toml
- Removes compilation feature `disable-metadata-hash-check`
- Adds struct `ExtrinsicParamsWithoutHashCheck` to still provide an "easy" compatibility with older nodes.
> Remove compilation feature `disable-metadata-hash-check`

- Cargo.lock
- primitives/Cargo.toml
- primitives/src/extrinsics/signer.rs
No need to import the full solochain for a single Signature Type.
> Remove obsolete solochain-template-runtime dev-dep

- docs/README.md
1.16 and 1.17 were tagged on the release branch, so I updated the dev docs accordingly.
Also, since it's not obvious, I also added the publish cmds (which need to be in order to work)
> Update dev docs with `cargo publish` cmds

- Cargo.lock
- about.toml
- examples/async/examples/check_extrinsic_events.rs
- primitives/src/extrinsics/extrinsic_params.rs
- primitives/src/extrinsics/extrinsic_params_without_hash_check.rs
- testing/async/examples/author_tests.rs
- Polkadot is working on adding support for decoding with a memory limit (`DecodeWithMemTracking`). Because of that we need additional trait bounds. See
- https://github.com/paritytech/polkadot-sdk/issues/7360
- The `webpki-root-certs` changed the license. For me the license looks good See: 
- https://github.com/rustls/webpki-roots/releases/tag/v%2F0.26.9
- https://cdla.dev/permissive-2-0/
- In two tests we get fewer events. I could not find a reason for that, but I also did not search for long.
> Fix nightly build job

- .github/workflows/ci.yml
- Cargo.lock
The following has been updated:
- cargo update
- wasm check has been disbaled. Reasoning: See https://github.com/scs/substrate-api-client/issues/513
> cargo update and disable wasm check

- .github/workflows/ci.yml
As Parity and the api-client are much more stable, a weekly build for checking upstream changes should be enough.
@Niederb do you agree?
Thanks for the input @dhobi-scs!
> CI: Change nightly build to weekly
